[tool.black]
line-length = 79

[tool.isort]
include_trailing_comma = true
line_length = 79
multi_line_output = 3

[tool.flake8]
per-file-ignores = ['gentoo_update/__init__.py:F401']
ignore = ["E203", "E501"]
max-line-length = 79
